<a href="https://colab.research.google.com/github/e23378-Tharz/computational-methods/blob/main/Copy_of_Practical01_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import os

data = np.array([
    [7, 20.0, 45.0],
    [8, 20.5, 45.4],
    [9, 21.0, 45.8],
    [10, 21.4, 46.2],
    [11, 21.8, 46.6],
    [12, 22.1, 47.0],
    [13, 22.3, 47.3],
    [14, 22.5, 47.6],
])

np.save("plane.npy", data)
print("Saved to:", os.path.abspath("plane.npy"))

Saved to: /content/plane.npy


In [ ]:
import numpy as np

data = np.load("plane.npy")

print(data)

[[ 7.  20.  45. ]
 [ 8.  20.5 45.4]
 [ 9.  21.  45.8]
 [10.  21.4 46.2]
 [11.  21.8 46.6]
 [12.  22.1 47. ]
 [13.  22.3 47.3]
 [14.  22.5 47.6]]


In [ ]:
t = data[:,0]
alpha_deg = data[:,1]
beta_deg = data[:,2]

print("Time =", t)
print("Alpha =", alpha_deg)
print("Beta =", beta_deg)

Time = [ 7.  8.  9. 10. 11. 12. 13. 14.]
Alpha = [20.  20.5 21.  21.4 21.8 22.1 22.3 22.5]
Beta = [45.  45.4 45.8 46.2 46.6 47.  47.3 47.6]


In [ ]:
alpha = np.deg2rad(alpha_deg)
beta = np.deg2rad(beta_deg)

print(alpha)
print(beta)

[0.34906585 0.3577925  0.36651914 0.37350046 0.38048178 0.38571776
 0.38920842 0.39269908]
[0.78539816 0.79237948 0.7993608  0.80634211 0.81332343 0.82030475
 0.82554074 0.83077672]


In [ ]:
a = 500

x = a * np.tan(beta) / (np.tan(beta) - np.tan(alpha))

y = a * np.tan(beta) * np.tan(alpha) / (np.tan(beta) - np.tan(alpha))

print("x =", x)
print("y =", y)

x = [786.12673013 792.01694265 797.81903447 801.04389292 804.16132426
 804.70606339 804.44953185 804.15453004]
y = [286.12673013 296.12300075 306.2540338  313.92566888 321.64158222
 326.75724814 329.92879757 333.09171258]


In [ ]:
h = 1

x_prime = np.zeros(len(x))
y_prime = np.zeros(len(y))

# Forward difference
x_prime[0] = (x[1] - x[0]) / h
y_prime[0] = (y[1] - y[0]) / h

# Centered difference
for i in range(1, len(x)-1):
    x_prime[i] = (x[i+1] - x[i-1]) / (2*h)
    y_prime[i] = (y[i+1] - y[i-1]) / (2*h)

# Backward difference
x_prime[-1] = (x[-1] - x[-2]) / h
y_prime[-1] = (y[-1] - y[-2]) / h

print("x' =", x_prime)
print("y' =", y_prime)

x' = [ 5.89021252  5.84615217  4.51347513  3.17114489  1.83108524  0.14410379
 -0.27576668 -0.29500181]
y' = [ 9.99627062 10.06365184  8.90133407  7.69377421  6.41578963  4.14360768
  3.16723222  3.16291501]


In [ ]:
v = np.sqrt(x_prime**2 + y_prime**2)

print("Speed =", v)

Speed = [11.60258721 11.63849576  9.98024077  8.32167781  6.67197345  4.1461127
  3.17921487  3.17664248]


In [ ]:
speed_change = np.diff(v)

largest_drop_index = np.argmin(speed_change)

print("Largest decrease occurs between:")
print(t[largest_drop_index], "and", t[largest_drop_index+1])

Largest decrease occurs between:
11.0 and 12.0


(b)
Condition:

is necessary because division by zero is undefined.
If:

then formulas for x and y cannot be computed.

(c)
Since the angle changes are gradual and nearly uniform, the airplane speed is expected to remain approximately constant.

(g)
Centered differences need values on both sides:

At endpoints there is no previous point or next point.
So forward/backward differences are used there.

Centered difference:
second-order accurate

Forward/backward:
first-order accurate

So one order of accuracy is lost at endpoints.

(j)
Speed is more sensitive to measurement noise because differentiation amplifies small errors.

(k)
If measurements are every 2 seconds:

h becomes larger

derivative approximations become less accurate

computed speed becomes less accurate